services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000
  user_microservice:
    build: ./user-microservice
    volumes:
      - ./user-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
  payment_microservice:
    build: ./payment-microservice
    volumes:
      - ./payment-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
