version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000

  user_microservice:
    build:
      context: ./user-microservice
      dockerfile: ../Dockerfile
    volumes:
      - ./user-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - mysql_db

  payment_microservice:
    build: ./payment-microservice
    volumes:
      - ./payment-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - mysql_db
  order_microservice:
    build: ./order-microservice
    volumes:
      - ./order-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - mysql_db
  auth_microservice:
    build:
      context: ./auth-microservice
      dockerfile: ../Dockerfile
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - mysql_db
    environment:
      - JWT_SECRET=cff69aa4-f4ad-47a7-b0c1-73a6ac1ef24c
  product_microservice:
    build:
      context: ./product-microservice
      dockerfile: ../Dockerfile
    volumes:
      - ./product-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - mysql_db
  cart_microservice:
    build:
      context: ./cart-microservice
      dockerfile: ../Dockerfile
    volumes:
      - ./cart-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - mysql_db
  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_db:
    image: mysql
    ports:
      - "3307:3306" # Host port:Container port
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
